language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
 - CODECEPT_VERSION="1.8.2" IMAGICK="imagick-3.3.0"
 - CODECEPT_VERSION="1.8.2" IMAGICK="imagick"
 - CODECEPT_VERSION="2.0.7" IMAGICK="imagick"
matrix:
  exclude:
    - php: 5.3
      env: CODECEPT_VERSION="1.8.2" IMAGICK="imagick"
    - php: 5.3
      env: CODECEPT_VERSION="2.0.7" IMAGICK="imagick"
    - php: 5.4
      env: CODECEPT_VERSION="1.8.2" IMAGICK="imagick-3.3.0"
    - php: 5.5
      env: CODECEPT_VERSION="1.8.2" IMAGICK="imagick-3.3.0"

before_script:
  - printf "\n" | pecl install ${IMAGICK}
  - phantomjs --webdriver=4444 --ignore-ssl-errors=true >/dev/null 2>&1 &
  - cd test/integration/
  - mkdir tests/_log
  - wget http://codeception.com/releases/${CODECEPT_VERSION}/codecept.phar
  - php codecept.phar build

script: php codecept.phar run -d