language: php

php:
  - 5.4
  - 5.5

before_script:
  - printf "\n" | pecl install imagick
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
  - java -jar selenium-server-standalone-2.35.0.jar -port 4444 > /dev/null &
  - cd test/integration/
  

script: php -d include_path="." codecept.phar run
