language: php

php:
  - 5.5
  - 5.6

env:
 - CODECEPT_VERSION="2.1"

matrix:
  exclude:
    - php: 5.3
      env: CODECEPT_VERSION="2"

before_script:
  - printf "\n" | pecl install imagick
  - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
  - java -jar selenium-server-standalone-2.53.0.jar -port 4444 >/dev/null 2>&1 &
  - cd test/integration/
  - mkdir tests/_log
  - php codecept${CODECEPT_VERSION}.phar build

script: php codecept${CODECEPT_VERSION}.phar run -d
