language: php

php:
  - 5.4
  - 5.5

before_script:
  - printf "\n" | pecl install imagick
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
  - java -jar selenium-server-standalone-2.35.0.jar -port 4444 >/dev/null 2>&1 &
  - cd test/integration/
  - mkdir tests/_log


script: php codecept.phar run -d