language: php

php:
  - 5.6
  - 7.0
  - 7.1


env:
 - IMAGICK="imagick-3.3.0"
 - IMAGICK="imagick"

before_script:
  - printf "\n" | pecl install ${IMAGICK}
  - phantomjs --webdriver=4444 --ignore-ssl-errors=true >/dev/null 2>&1 &
  - composer install
  - php vendor/bin/codecept build

script: php vendor/bin/codecept run -c test/integration/