name: "CI"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests on docker compose
        run: docker compose up --abort-on-container-exit
